import { test, expect } from '@playwright/test';

test.use({
  ignoreHTTPSErrors: true,
  locale: 'en-US'
});

test('test', async ({ page }) => {
  await page.goto('https://magic.estudionk.com/');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Explore' }).click();
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Explore' }).press('ArrowDown');
  await page.locator('body').click();
});